// Generated by ReScript, PLEASE EDIT WITH CARE

import * as Belt_Array from "bs-platform/lib/es6/belt_Array.js";

var body = document.body;

function make(title, author, text) {
  return {
          title: title,
          author: author,
          text: text
        };
}

function title(t) {
  return t.title;
}

function author(t) {
  return t.author;
}

function text(t) {
  return t.text;
}

var Post = {
  make: make,
  title: title,
  author: author,
  text: text
};

var posts = [
  {
    title: "The Razor's Edge",
    author: "W. Somerset Maugham",
    text: [
      "\"I couldn't go back now. I'm on the threshold. I see vast lands of the spirit stretching out before me,\n    beckoning, and I'm eager to travel them.\"",
      "\"What do you expect to find in them?\"",
      "\"The answers to my questions. I want to make up my mind whether God is or God is not. I want to find out why\n    evil exists. I want to know whether I have an immortal soul or whether when I die it's the end.\""
    ]
  },
  {
    title: "Ship of Destiny",
    author: "Robin Hobb",
    text: [
      "He suddenly recalled a callow boy telling his tutor that he dreaded the sea voyage home, because he would have\n        to be among common men rather than thoughtful acolytes like himself. What had he said to Berandol?",
      "\"Good enough men, but not like us.\"",
      "Then, he had despised the sort of life where simply getting from day to day prevented a man from ever taking\n        stock of himself. Berandol had hinted to him then that a time out in the world might change his image of folk\n        who labored every day for their bread. Had it? Or had it changed his image of acolytes who spent so much time in\n        self-examination that they never truly experienced life?"
    ]
  },
  {
    title: "A Guide for the Perplexed: Conversations with Paul Cronin",
    author: "Werner Herzog",
    text: ["Our culture today, especially television, infantilises us. The indignity of it kills our imagination. May I propose a Herzog dictum? Those who read own the world. Those who watch television lose it. Sitting at home on your own, in front of the screen, is a very different experience from being in the communal spaces of the world, those centres of collective dreaming. Television creates loneliness. This is why sitcoms have added laughter tracks which try to cheat you out of your solitude. Television is a reflection of the world in which we live, designed to appeal to the lowest common denominator. It kills spontaneous imagination and destroys our ability to entertain ourselves, painfully erasing our patience and sensitivity to significant detail."]
  }
];

function createTag(tag) {
  return document.createElement(tag);
}

function addClass(element, cl) {
  element.className = cl;
  return element;
}

function addId(element, id) {
  element.setAttribute("id", id);
  return element;
}

function appendChild(child, parent) {
  return parent.appendChild(child);
}

function createTextnode(element, text) {
  element.innerHTML = text;
  return element;
}

function findElementbyId(id) {
  return document.getElementById(id);
}

function deleteText(post) {
  return "This post from <em>" + post.title + " by " + post.author + "</em> will be permanently removed in 10 seconds.";
}

var Tag = {
  createTag: createTag,
  addClass: addClass,
  addId: addId,
  appendChild: appendChild,
  createTextnode: createTextnode,
  findElementbyId: findElementbyId,
  deleteText: deleteText
};

function restore(postDiv, post_id) {
  var id = "block-" + String(post_id);
  var deleteDiv = document.getElementById(id);
  body.insertBefore(postDiv, deleteDiv);
  return body.removeChild(deleteDiv);
}

function deleteElement(post_id) {
  var id = "block-" + String(post_id);
  var deleteDiv = document.getElementById(id);
  return body.removeChild(deleteDiv);
}

function $$clearInterval(intervalId) {
  return window.clearInterval(intervalId);
}

var $$Function = {
  restore: restore,
  deleteElement: deleteElement,
  $$clearInterval: $$clearInterval
};

function createDeleteNotif(post, postDiv, id, intervalId) {
  var deleteDiv = addClass(addId(document.createElement("div"), "block-" + String(id)), "post-deleted pt-1");
  var postHeadingTag = createTextnode(addClass(document.createElement("p"), "text-center"), deleteText(post));
  deleteDiv.appendChild(postHeadingTag);
  var buttonDiv = addClass(document.createElement("div"), "flex-center");
  var restoreButton = createTextnode(addClass(addId(document.createElement("button"), "block-restore-" + String(id)), "button button-warning mr-1"), "Restore");
  restoreButton.addEventListener("click", (function (param) {
          restore(postDiv, id);
          return window.clearInterval(intervalId);
        }));
  buttonDiv.appendChild(restoreButton);
  var deleteImmediatelyButton = createTextnode(addClass(addId(document.createElement("button"), "block-delete-immediate-" + String(id)), "button button-danger"), "Delete Immediately");
  deleteImmediatelyButton.addEventListener("click", (function (param) {
          deleteElement(id);
          return window.clearInterval(intervalId);
        }));
  buttonDiv.appendChild(deleteImmediatelyButton);
  deleteDiv.appendChild(buttonDiv);
  var animationDiv = addClass(document.createElement("div"), "post-deleted-progress");
  deleteDiv.appendChild(animationDiv);
  return deleteDiv;
}

function showDeleteNotif(post, index) {
  var id = "block-" + String(index);
  var postDiv = document.getElementById(id);
  var intervalId = window.setTimeout((function (param) {
          return deleteElement(index);
        }), 10000);
  var deleteDiv = createDeleteNotif(post, postDiv, index, intervalId);
  body.insertBefore(deleteDiv, postDiv);
  return body.removeChild(postDiv);
}

function createPostView(post, id) {
  var postDiv = addClass(addId(document.createElement("div"), "block-" + String(id)), "post");
  var postHeadingTag = createTextnode(addClass(document.createElement("h2"), "post-heading"), post.title);
  postDiv.appendChild(postHeadingTag);
  var postAuthorTag = createTextnode(document.createElement("h3"), post.author);
  postDiv.appendChild(postAuthorTag);
  Belt_Array.forEach(post.text, (function (line) {
          var child = createTextnode(addClass(document.createElement("p"), "post-text"), line);
          return postDiv.appendChild(child);
        }));
  var button = createTextnode(addClass(addId(document.createElement("button"), "block-" + String(id)), "button button-danger"), "Remove this post");
  button.addEventListener("click", (function (param) {
          return showDeleteNotif(post, id);
        }));
  postDiv.appendChild(button);
  return postDiv;
}

var View = {
  createDeleteNotif: createDeleteNotif,
  showDeleteNotif: showDeleteNotif,
  createPostView: createPostView
};

function createPost(param) {
  return Belt_Array.forEachWithIndex(posts, (function (index, post) {
                var postDiv = createPostView(post, index);
                return body.appendChild(postDiv);
              }));
}

var DelayedPostRemoval = {
  createPost: createPost
};

createPost(undefined);

export {
  body ,
  Post ,
  posts ,
  Tag ,
  $$Function ,
  View ,
  DelayedPostRemoval ,
  
}
/* body Not a pure module */
